### ISSUE TITLE
ヘッダファイルかつグローバル名前空間でusing directiveしてはいけない

### ISSUE THREAD

**Issue by faithandbrave** [yohokuno/stakk#1]
現在、common.hで using namespace std; されていますが、ヘッダファイルかつグローバル名前空間でこれを行うのは御法度です。
このライブラリを使用するユーザーに、名前衝突を起こす危険性を強制することになってしまいますので、これは修正していただきたいです。

**Comment by yohokuno** [comment]
修正しました。お手数ですが、再度リポジトリよりチェックアウトをお願いします。

パッケージの修正は少々お待ちください。
